version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME:-username}/skin-cancer-frontend:latest
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_BACK_END_URL=http://backend:4000
      - VITE_ML_API_URL=http://ml-api:5001
    depends_on:
      - backend
      - ml-api
    networks:
      - app-network

  backend:
    image: ${DOCKER_USERNAME:-username}/skin-cancer-backend:latest
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=prod
      - PROD_PORT=4000
      - PROD_MONGO_URI=mongodb+srv://skinocare:skinocare@skinocare-prod.vdn9n.mongodb.net/
    networks:
      - app-network
    volumes:
      - ./backend/cancers.json:/app/cancers.json

  ml-api:
    image: ${DOCKER_USERNAME:-username}/skin-cancer-ml-api:latest
    build:
      context: ./Ml_Model
      dockerfile: dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./Ml_Model/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local